import Head from 'next/head';
import { Jost } from '@next/font/google';
import Header from '@/wrappers/header/Header';
import styles from '@/styles/home.module.scss';

const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '700']
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={jost.className}>
        <Header />
      </main>
    </>
  );
}
